name: telebirrbybr7
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & fonts
  cupertino_icons: ^1.0.2
  text_scroll: ^0.2.0
  marquee: ^2.2.3
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0

  # Carousels & navigation
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  dots_indicator: ^4.0.1
  flutter_sticky_widgets: ^0.0.3
  dot_navigation_bar: ^1.0.2

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1

  # SMS functionality (Using Git fix for SmsManager error on Samsung S9+)
  telephony:
    git:
      url: https://github.com/suhardik/Telephony.git
      ref: fix-sms-controller-error

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/br7logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/ethio.png
    - images/telebirr.png
    - images/cbe.png
    - images/dashen.png
    - images/Bg1.png
    - images/Banner1.jpg
    - images/Banner2.jpg
    - images/Banner3.jpg
    - images/Banner4.jpg
    - images/Banner5.jpg
    - images/Airtime.jpg
    - images/Cashinout.jpg
    - images/Devicefin.jpg
    - images/Lottery.jpg
    - images/More.jpg
    - images/Paymerchant.jpg
    - images/Teleev.jpg
    - images/Transfertobank.jpg
    - images/Sinqee.png
    - images/Zemen.png
    - images/Fyda.png
    - images/Awash.png
    - images/ethio-logo.png
    - images/christmas.png
    - images/br7logo.png
    - images/Test.jpg
    - images/home_icon.png
    - images/payment_icon.png
    - images/apps_icon.png
    - images/engage_icon.png
    - images/account_icon.png
    - images/bottom_bar.jpg
